const express = require('express')
const router = express.Router()
const {read,remove,list,create,update} =require('../controllers/product')
const {auth}= require("../Middleware/auth")
const {upload}= require("../Middleware/upload")
router.get('/product',list)
router.get('/product/:id',read)
router.post('/product',upload,create)
router.put('/product/:id',upload,update)
router.delete('/product/:id',remove)
module.exports =  router
